### ISSUE TITLE
better syntax for specifying render method

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#149]
allow the render method to be specified like this:

``` ruby
  class Foo < React::Component::Base 
    render do 
      div.foo do 
        "hello".span
        "there".span 
      end
    end
  end
```

as an alternative to

``` ruby
  class Foo < React::Component::Base 
    def render
      div.foo do 
        "hello".span
        "there".span 
      end
    end
  end
```

Why? 
1. render methods are very often longer than the 10 lines recommend by style guides.  Specifying the render method as a block avoids linter (i.e. rubocop) errors.
2. we can now also specify the container as the first parameter, shortening things up:

``` ruby
class Foo < React::Component::Base 
  render(:div, class: :foo) do 
    "hello".span
    "there".span 
  end
end
```

**Comment by catmando** [comment]
an alternative would be to assume a :div unless something else was specified.

If nil was specified then the container would be defined by the block:

``` ruby
class Foo < React::Component::Base
  render do
    "hello".span
    "there".span
  end
end
```

``` ruby
class FooBar < React::Component::Base 
  render(MyComponent, some_param: 1) do
    ...
  end
end
```

``` ruby
class Fob < React::Component::Base 
  render(nil) do
     if do_it_this_way 
      div { "i'm a div" }
     else
       "i'm a span".span
     end
  end
end
```

**Comment by fkchang** [comment]
I don't really see a need for this if the primary reason is because rubocop or similar complains that it's over 10 lines.  That's like saying html, haml, etc. can't be longer than 10 lines, which is kind of silly.  On default components, I'm on the fence, because it's not intuitive to me what it means, though obviously one can get it over.  The normal expression, while more verbose, is explicit and doesn't need explanation, but I can see haml fans liking the increased brevity

**Comment by loicboutet** [comment]
I'm not sure I like this syntax. To me it makes the render "magic" and not just another method. 
If the problem is rubocop I guess we could add the necessary comments to it to not bother you with it inside the generator

**Comment by elia** [comment]
I too dislike adapting code to work around a tool that is intended to help. 
Otherwise it should be renamed SkyNET! 🤖 

As for the div wrapper I'd like to just point out that Inesita does that adding a `div` if it sees more than one root. But I'd avoid the inline options (i.e. `render(:div, class: :foo)`).

**Comment by catmando** [comment]
@elia - well I am using rubocop as an automation for the ruby style guide. d

Lets put it this way several years ago, if @zetachang had said.... hmmm.... how will I specify what to render.... hmmm... I could just add another hook, called render... I think we would all be happy with that.  (well maybe not) I don't know.

Its all components have to render some element, so why not let that element be specified optionally as a parameter to a hook, instead of this kind of redundant

``` ruby
def render
  div do
    ....
  end
end
```

its just two extra lines you have to have with every component, and more over most of the time its going to be a div so just default that as well.

The inestia solution is not really helpful it the our case, as we would typically need to pass in params like the class or styles

**Comment by catmando** [comment]
@loicboutet - I'm not seeing why a render call back hook is any more magic than the before_mount hook
