### ISSUE TITLE
need be able to import / use JS stateless components

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#184]
I am not sure what exactly is needed to make this work...

but as @fkchang points out there are quite a few JS libs that have stateless components... These things are just JS functions I guess (from the reading the docs) 

I think the use case would be that if I import a library (or autoimport) and it contains a stateless function foo, then I should be able to call Foo(...) as normal....  

In otherwords it should look like any other component call. 

Here is an example library that uses these...

http://blueprintjs.com/

**Comment by catmando** [comment]
I also don't quite understand if there is any rendering implication with these... in otherwords are these any different than just making a function call?  Or does react.js only "rerender" them if their props change like any other component...

**Comment by zetachang** [comment]
I think this is already addressed in #162 ? Or do you bump into any bug while using it?

**Comment by catmando** [comment]
huh @fkchang reported this... I may have misunderstood him, perhaps it is not working?

The one thing to still look at is how react.js treats these from the callers perspective..

**Comment by fkchang** [comment]
#162 did fix this, I verified it and reported it on gitter - sorry I wasn't clear enough, I was originally asking because I wasn't sure if it was fixed.  As reference container classes, like ButtonGroup, from reactstrap (react bindings to bootstrap 4 components) are done as pure functional components.  I verified #162's fix by using ButtonGroup.  Closing this
