### ISSUE TITLE
Checklist for releasing 0.12.0

### ISSUE THREAD

**Issue by zetachang** [ruby-hyperloop/hyper-react#205]
- [ ] make sure docs is updated
- [ ] hyper-rails generator update https://github.com/ruby-hyperloop/hyper-rails/pull/8

**Comment by catmando** [comment]
@zetachang - we are churning away on finalizing how the full hyperloop system is going to work, and will introduce some new methods in the DSL, plus there is a possibly breaking change/fix in the State module, etc, etc.

So before we release unless you think otherwise, I would like to those items in (since its a major release.)

**Comment by zetachang** [comment]
Sure, I am fine with it. Just created a milestone called **0.12.0**. Feel free to add issue to that milestone.

**Comment by barriehadfield** [comment]
@zetachang I am very happy to do the docs and the generator work so please feel free to assign things to me and I will do them. All I need to understand is what needs to be changed

**Comment by zetachang** [comment]
@barriehadfield great! Will let you know if I need any help.

**Comment by zetachang** [comment]
@catmando as #208 arise, it would become harder to support both ES6 style `React.Component` and `React.createClass`. Thus I think it's time that we can drop support of React v13 maybe in next release ?

**Comment by janbiedermann** [comment]
Thats the past.
lap20 supports react 16 only.
