### ISSUE TITLE
Travis failures - bad config

### ISSUE THREAD

**Issue by sfcgeorge** [ruby-hyperloop/hyper-react#221]
Looks like Travis has been partly failing for a while. This isn't ideal as you can quickly spiral into ignoring more and more errors until the whole test suite is broken and you're merging blind.

One issue seems to be missing jRuby binary. 

The other issue is missing PhantomJS download, for an ancient version.

As per #201 we should stop supporting ancient versions of Ruby / jRuby / PhantomJS,  aka just delete those Travis configs. Currently Travis only tests up to Ruby 2.1 so it would be good to add 2.4 to the matrix.

**Comment by janbiedermann** [comment]
most of this is done in sachsenring, yet travis config needs to be updated to use -pre gems
we use chromes headless driver to drive the test.

**Comment by janbiedermann** [comment]
Travis is absolutely useless for this project. Tests are completely unreliable and subtle versions changes result in failures **ONLY ON TRAVIS**. I guess that is, because they only provide ancient dinosaur software, where various bugs, long ago fixed in modern of versions of that basic software, are present all over the place.
